spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:mem:popcon
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
          portOneBillingClient:
            connectTimeout: 3000
            readTimeout: 10000

portone:
  api:
    secret: ${PORTONE_API_SECRET}
    store-id: ${PORTONE_STORE_ID}
  url: "https://api.portone.io"
  channel-key: ${PORTONE_CHANNEL_KEY}

encryption:
  secret: ${ENCRYPTION_SECRET}

user:
  nickname:
    prefix: ${NICKNAME_PREFIX}
    
internal:
  api-secret: ${INTERNAL_API_SECRET}

services:
  draw-service:
    url: ${DRAW_SERVICE_URL}
  auction-service:
    url: ${AUCTION_SERVICE_URL}
  ticket-service:
    url: ${TICKET_SERVICE_URL}
  popup-service:
    url: ${POPUP_SERVICE_URL}

s3:
  endpoint: ${S3_ENDPOINT}
  bucket: ${S3_BUCKET}
  region: ${S3_REGION:ap-northeast-2}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  base-url: ${S3_BASE_URL}
